# Generated by Django 5.0.4 on 2024-04-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
